### ISSUE TITLE
Gears 5 fails

### ISSUE THREAD

**Issue by Blenux** [Wunkolo/UWPDumper#18]
Hi looks like they bloke access in the newest game.

![Annotation 2019-09-07 133107](https://user-images.githubusercontent.com/25260650/64469781-71af3080-d17b-11e9-9531-39e59c79c1ed.png)

**Comment by Wunkolo** [comment]
Looks like gears 5 has some kernel level drm
https://twitter.com/axelgneiting/status/1170399294463053825?s=19
