### ISSUE TITLE
Fails to inject Halo: The Master Chief Collection

### ISSUE THREAD

**Issue by Nun-z** [Wunkolo/UWPDumper#23]
When I try to inject Halo : TMCC, I get the following error: unable to remotely allocate memory.

**Comment by Wunkolo** [comment]
You might need to run the game with the Easy Anti Cheat disabled.
[Check out this guide](https://www.reddit.com/r/halomods/comments/e5tsmu/dumping_the_ms_store_version_of_halo_mcc/)

**Comment by Nun-z** [comment]
Thanks, it worked after disabling Easy Anti Cheat.
