### ISSUE TITLE
Bluescreen: UNEXPECTED_KERNEL_MODE_TRAP

### ISSUE THREAD

**Issue by Symbai** [Wunkolo/UWPDumper#27]
Trying to dump Pillars Of Eternity included in Windows 10 Game Pass always results in a bluescreen `UNEXPECTED_KERNEL_MODE_TRAP`.

The console window last entry is the **expected** dump directory (i.e. the console is showing up to this point: https://github.com/Wunkolo/UWPDumper/blob/9fb0a040e674521c1413276bcea6e4e708f34d19/UWPDumper/main.cpp#L87). It is not even listening any file to dump.

If you have the Windows 10 Game Pass subscription for $1 you have access to the game and should be able to repro.

**Comment by tunip3** [comment]
I have attempted to dump this game but have not encountered any similar issues. Do you have another machine you could try to replicate this on?

**Comment by Symbai** [comment]
No, but this is the only game/app where this happens and it happens constantly on this game. So I am able to repro this and provide information is necessary.

**Comment by tunip3** [comment]
have you tried the latest version?
