### ISSUE TITLE
VCRUNTIME140_1.dll not found (x64) / Remote Thread (x86)

### ISSUE THREAD

**Issue by NextGen8** [Wunkolo/UWPDumper#28]
**One** of these issues has been described already by another user, however I don't believe the _vcruntime_ issue has.
![x64](https://user-images.githubusercontent.com/57649271/71651265-2dc3d680-2cea-11ea-9562-1bec7a47ee5f.png)
![x86](https://user-images.githubusercontent.com/57649271/71651268-31eff400-2cea-11ea-8aef-ecaa13cdf7d2.png)

**Comment by Wunkolo** [comment]
Not having `VCRUNTIME140` implies that you are missing one of the Visual C++ runtimes. I believe `v140` is the [Visual Studio 2015 runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48145).
Also ensure that your target process and injector architecture are both x32 or x64 bit.

**Comment by NextGen8** [comment]
Well. Turns out Bitdefender doesn't like Visual Studio Runtime, so I had to turn Bitdefender off to install the files. After this I also had to add UWPDumper as an exception because it kept calling it a virus. So this worked... As well as me not realizing that trying to dump a Game running in x64 with x32 isnt gonna work... Thank You!
