### ISSUE TITLE
Long path/filename write issues

### ISSUE THREAD

**Issue by mrpijey** [Wunkolo/UWPDumper#29]
Seems during dumping of some games you get write file errors

`
Error opening C:\Users\User\AppData\Local\Packages\ParadoxInteractive.PillarsofEternity-MicrosoftStor_zfnrdv2de78ny\TempState\DUMP\PillarsOfEternity_Data\data\localized\es\text\conversations\01_defiance_bay_copperlane\01_bs_controller_crucible_knight.stringtable for writing

Error opening C:\Users\User\AppData\Local\Packages\ParadoxInteractive.PillarsofEternity-MicrosoftStor_zfnrdv2de78ny\TempState\DUMP\PillarsOfEternity_Data\data_expansion1\localized\it\text\conversations\px1_00_stalwart_village\px1_00_bs_ambient_banters.stringtable for writing
`
Lots and lots of these with Pillars of Eternity for example, but also discovered it with some other titles. I seems the path is too long and then it will not save the file at all. Can this be fixed somehow as NTFS supports much longer paths in reality. I have the GPO set for LFN support but it seems to not work with the dumper tool. I can create filenames and paths longer manually so it's not an OS issue.

**Comment by Wunkolo** [comment]
Sorry for the delay, have you ran into this issue again at all?
The path `C:\Users\User\AppData\Local\Packages\ParadoxInteractive.PillarsofEternity-MicrosoftStor_zfnrdv2de78ny\TempState\DUMP\PillarsOfEternity_Data\data_expansion1\localized\it\text\conversations\px1_00_stalwart_village\px1_00_bs_ambient_banters.stringtable` is 249 characters total. Which should be totally fine as there is no intermediate fixed-sized buffer that would cause issues with larger file sizes unless there is(or was) an internal limitation with `std::filesystem::path` that causes this.

**Comment by Measurity** [comment]
Got the same issue with a path of 262 when dumping Subnautica files:
```
Error opening C:\Users\Measurity\AppData\Local\Packages\UnknownWorldsEntertainmen.GAMEPREVIEWSubnautica_bh1f6rvenfkm2\TempState\DUMP\Subnautica_Data\StreamingAssets\aa\StandaloneWindows64\aurora_livingarea_captainsquarters_keypad.prefab_5df5cc80af0f62fae7638855ed38c38f.bundle for writing
```
This path is 262 characters long.

**Comment by thule0** [comment]
Can confirm, Subnautica cannot be dumped, and the '-d' switch is entirely ignored.

**Comment by mrpijey** [comment]
It's a long path issue. Solved manually by copying out the files manually, since only the exes are encrypted everything else can be copied out just fine.

Would be nice if this could be addressed since Windows does support long paths, so only the right APIs needs to be used for reading and writing.
