### ISSUE TITLE
Files still locked after dumping

### ISSUE THREAD

**Issue by RT-EB** [Wunkolo/UWPDumper#3]
Guess this has to do with the new update? Never had this issue before.

Talking about Forza Horizon 3 btw.

**Comment by Apollo-X** [comment]
I noticed from hw2 that they still show the lock icon for files and folders act as if still locked but if you try copying the files from folder elsewhere to take a look, it probably works fine.

**Comment by Wunkolo** [comment]
Some of the more recent updates should fix your issue. Be sure to download the latest build from AppVeyor

**Comment by Scrxtchy** [comment]
Getting this a couple times when I try to copy the folder
![image](https://user-images.githubusercontent.com/12771982/42291508-75aa4c1a-800f-11e8-90f9-a71c8be21895.png)

Fastest way around it is to tar then and move the tar elsewhere, as most likely the folder is taken over by NTFS inheritance / encryption

**Comment by umustbeloggedintododat** [comment]
how do I tar?

**Comment by Scrxtchy** [comment]
I use 7zip

**Comment by Mask-Ninja** [comment]
> Getting this a couple times when I try to copy the folder ![image](https://user-images.githubusercontent.com/12771982/42291508-75aa4c1a-800f-11e8-90f9-a71c8be21895.png)
> 
> Fastest way around it is to tar then and move the tar elsewhere, as most likely the folder is taken over by NTFS inheritance / encryption

Oh yeah, just saying, if you for some reason can't use 7Z, then try copy-pasting the files. The folders don't work. But you have to do everything manually.
