### ISSUE TITLE
Add logging option

### ISSUE THREAD

**Issue by mrpijey** [Wunkolo/UWPDumper#30]
Would be beneficial with a log stored with the dump of what's been dumped and an additional error log of any issues during the dumping. Since many games has thousands upon thousands of files it's sometimes important to know what files it weren't able to dump.

**Comment by tunip3** [comment]
would it be acceptable to log automatically or would it have to be a command line flag?

**Comment by Wunkolo** [comment]
It would be better as a command line option though in its current state it would be fine to log all the time so that users can properly have a means diagnose cases where dumping fails.

**Comment by Wunkolo** [comment]
I've dome some adjustments after merging your PR to clean up some of the file logging structure and to protect against some heap corruptions that were happening when interpreting `std::wstrings` in the shared IPC memory region.

This is the commit: https://github.com/Wunkolo/UWPDumper/commit/2883ab4e81d1a6035f4c3c047d78b544434bdd63

```
Log files will now use an ISO-8601 format time stamp
as well as the package name to resolve the file name.

ISO-8601 is selected as the files are monotonically increasing
so sorting by file-name will also sort by time. The package name
is also used in the file name rather than the .exe name in protect
against the case in which separate winapp packages use the same
executable name despite being different packages.
```

Dump log files will look like this now:

![explorer_rMGGoWbvxp](https://user-images.githubusercontent.com/644247/96356522-9545e980-10a4-11eb-82be-50a8bab2be1d.png)

**Comment by tunip3** [comment]
I think this issue can now be closed
