### ISSUE TITLE
Halo MCC Fails to open any EFS files to copy

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [Wunkolo/UWPDumper#31]
![image](https://user-images.githubusercontent.com/33284629/75892568-75212d00-5e29-11ea-9872-3a2edc3877a3.png)

**Comment by Wykillin** [comment]
I have the same problem. Thank you

**Comment by SuperMario20** [comment]
I also have this same issue.

**Comment by SuperMario20** [comment]
Ok, apparently I found a workaround for this. Apparently, according to @Zoomboli on reddit, "You no longer have to dump it as Microsoft does it for you. Fully install it from the store and then go to program files and look for a folder called Modifiable Windows apps." Can confirm this works.
