### ISSUE TITLE
UWPdumper doesn't download

### ISSUE THREAD

**Issue by matiaspor** [Wunkolo/UWPDumper#34]
When you press Download latest x64 binary here it says this:

_**This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:66e961a9-c01e-0030-4399-63cf27000000 Time:2020-07-26T22:07:44.4110188Z</Message>
</Error>**_

Need help.

**Comment by Wunkolo** [comment]
I seemed to be getting this too.
The artifacts list on AppVeyor seems to say that there are no artifacts anymore, and gave me this message too:
```
Artifacts older than 6 months are automatically deleted. For more details see Artifacts retention policy.
```
I kicked off a new build and now the download links work. 👍
