### ISSUE TITLE
Access denied for dump path

### ISSUE THREAD

**Issue by BasPaap** [Wunkolo/UWPDumper#42]
I'm trying to dump Sea of Thieves but I get an Access Denied error for every sub folder it is trying to create. The files themselves don't seem to give any error but my dump folder remains empty.

Here's a sample of the error messages I get:

>Injecting into remote process: Success!
>Waiting for remote thread IPC:
>Remote Dumper thread found: 0x2508
>DLL Attached to process 4948
>Creating dumper thread1869681232
>UWPDumper Build date(Oct 24 2020 : 02:52:26)
>        -https://github.com/Wunkolo/UWPDumper
>Publisher:
>        CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
>Publisher ID:
>        8wekyb3d8bbwe
>Publisher Path:
>        \AppData\Local\Publishers\8wekyb3d8bbwe
>Package Path:
>        C:\Program Files\WindowsApps\Microsoft.SeaofThieves_2.95.6160.2_x64__8wekyb3d8bbwe
>Package Name:
>        Microsoft.SeaofThieves_2.95.6160.2_x64__8wekyb3d8bbwe
>Family Name:
>        Microsoft.SeaofThieves_8wekyb3d8bbwe
>Dump Path:
>        C:\Users\foo\AppData\Local\Packages\Microsoft.SeaofThieves_8wekyb3d8bbwe\TempState\DUMP
>        Dumping 1099 files
>SeaofThieves_2.95.6160.2_x64__8wekyb3d8bbwe\AppxBlockMap.xml        50317739 bytes                    1/1099
>Error creating subfolder: C:\Users\foo\AppData\Local\Packages\Microsoft.SeaofThieves_8wekyb3d8bbwe\TempState\DUMP
>        Access denied.
>SeaofThieves_2.95.6160.2_x64__8wekyb3d8bbwe\AppxManifest.xml           12301 bytes                    2/1099
>Error creating subfolder: C:\Users\foo\AppData\Local\Packages\Microsoft.SeaofThieves_8wekyb3d8bbwe\TempState\DUMP
>        Access denied.
>.95.6160.2_x64__8wekyb3d8bbwe\AppxMetadata\CodeIntegrity.cat           14800 bytes                    3/1099
>Error creating subfolder: C:\Users\foo\AppData\Local\Packages\Microsoft.SeaofThieves_8wekyb3d8bbwe\TempState\DUMP\AppxMetadata
>        Access denied.`

Etc. I'm running this from a PowerShell console with administrator privileges. I also tried dumping Calculator as per the example but I get the same errors. Any ideas?

**Comment by BasPaap** [comment]
This appears to be fixed as of https://github.com/Wunkolo/UWPDumper/pull/43

**Comment by wh0am15533** [comment]
No it isn't, you must make sure the folder your dumping to with -d exists. If it doesn't exist, you get the permission errors. You should create the folder before dumping. Not just user's but you should add to the project.
