### ISSUE TITLE
Dumping Error for Halo Wars: Definitive Edition

### ISSUE THREAD

**Issue by SuperMario20** [Wunkolo/UWPDumper#44]
When I dump Halo Wars: DE for modding and run the "uwp_install_apps.bat", it just uninstalls the normal game and then says success but it didn't work because of an error. It gave the error: 

Package Microsoft.BulldogThreshold_1.12186.1.2_x64__8wekyb3d8bbwe with Windows Store origin cannot be sideloaded or     installed using developer mode option.

Does this mean UWPDumper won't work anymore because of a windows store patch?

**Comment by Wunkolo** [comment]
It might mean that some UWP software disable the ability to sideload it after it has been packaged up for purely client use.
Halo Wars: DE seems to intentionally block the ability to sideload it as a form of copy-protection.
