### ISSUE TITLE
Remote thread wait timeout: Unable to find target thread Press any key to continue . . .

### ISSUE THREAD

**Issue by lan852** [Wunkolo/UWPDumper#47]
Remote thread wait timeout: Unable to find target thread
Press any key to continue . . .
please help me

**Comment by lan852** [comment]
Injecting into remote process: Success!
Waiting for remote thread IPC:
Remote thread wait timeout: Unable to find target thread
Press any key to continue . . .

**Comment by Wunkolo** [comment]
This is not enough contextual information.

**Comment by lan852** [comment]
The new game named Undertale (PC) can not be dumped

**Comment by Wunkolo** [comment]
This indicates that it is unable to connect to the remote dump thread in the target process, which means the injected process is not spawning the "phone home" side of the dumping process. There is not enough insight on this issue to figure out why though.
