### ISSUE TITLE
"Error copying" on Windows Creator Update

### ISSUE THREAD

**Issue by CMPXCHG8B** [Wunkolo/UWPDumper#5]
I'm trying to run uwpdumper and receiving the attached error. This is on a system running Windows 10 version 1703, with a fresh copy of Halo 5 Forge downloaded and installed.

No matter what I do, I always get the same error. I have tried taking ownership of the WindowsApps folder (which I can now browse, but not modify). The permissions on the AppData\Local\Packages folder seems fine, UWPDumper is able to create a few files (see second attachment) but it always bombs out at exactly the same place. I tried commenting out the return statement (return EXIT_FAILURE) to see if it'd continue dumping files regardless, but it just creates a whole lot of empty folders and nothing else gets decrypted.

Is UWPDumper still working these days? Or did Microsoft patch things so it wouldn't work? Oddly enough, I have a friend who successfully ran the tool in the past 24 hours and he had no problems whatsoever. I've tried reformatting this system twice now and re-installing H5F both times, and I've even tried compiling UWPDumper from source (using MSVS2017). I always get the same error.

![capture](https://user-images.githubusercontent.com/4461291/30411466-e9ba5e60-98c5-11e7-9782-175c0c6b7c21.PNG)

![capture_2](https://user-images.githubusercontent.com/4461291/30411471-ef5bd7a4-98c5-11e7-8171-5ebac4e067b2.PNG)

**Comment by CMPXCHG8B** [comment]
Nevermind, it seems like the patch mentioned in this issue fixed it:

https://github.com/Wunkolo/UWPDumper/issues/2

Oddly enough, the version in the develop branch doesn't work- it just errors out on everything, and creates a bunch of 0kb files in the process. For whatever reason, Bennett's patch worked fine though.

**Comment by SuperShifty** [comment]
I'm currently having this issue on Windows 10 version **1709** (Build 16288.1), I tried the patch mentioned but then I get 
`Remote thread wait timeout: Unable to find target thread`

Same result when using the dev build with or without the patch.

**Comment by V7X3** [comment]
I got that issue with a debug build + the patch
However, a release build + the patch + running as admin works perfectly (just dumped Cuphead)
