### ISSUE TITLE
When install link clicked, error message displays : {"message":"Artifact not found or access denied."}

### ISSUE THREAD

**Issue by BlueFalconHD** [Wunkolo/UWPDumper#51]
I clicked this link:
Download latest x64 binary here!
URL:
https://ci.appveyor.com/api/projects/Wunkolo/uwpdumper/artifacts/UWPDumper-x64.zip?job=Platform%3A+x64
Error:
{"message":"Artifact not found or access denied."}

IDK what this means. Please Help!

**Comment by Cwa03** [comment]
I've got the same issue, this appeared since yesterday i guess.

**Comment by GabrielGabilan** [comment]
Someone who has the file could upload it on google drive or another platform so that we can download it

**Comment by Wunkolo** [comment]
Fix it. Looks like Appveyor deletes build artifacts after a while. I started a new built and the links now work.

**Comment by Hinkiii** [comment]
It's gone again

**Comment by Wunkolo** [comment]
Kicked off another build

**Comment by Hinkiii** [comment]
Could be worth uploading as a GitHub release if you think this build will be around for a bit
