### ISSUE TITLE
Do not pause when tool can run autonomously (i.e. when arguments are supplied)

### ISSUE THREAD

**Issue by Measurity** [Wunkolo/UWPDumper#53]
Would be nice so it does not require user input to unpause when using this tool as part of an automated procedure. In addition it does not need to open the DUMP folder when done.

**Code that causes "issue"**
https://github.com/Wunkolo/UWPDumper/blob/c29e9d654d8743049ecc082ba8a414731f727a6e/UWPInjector/source/main.cpp#L413

This code always opens DUMP folder when done but when it's part of automated procedure this can be confusing (and it doesn't open a custom dump directory if specified with -d).
https://github.com/Wunkolo/UWPDumper/blob/c29e9d654d8743049ecc082ba8a414731f727a6e/UWPDumper/main.cpp#L66-L69

**Example of how I use it**
https://github.com/Measurity/AddModSupportMSStoreSubnautica/blob/8bf149f0d32862f9507a47118fa4dadbab8fcd0a/AddModSupportMSStoreSubnautica/Program.cs#L47

**Comment by Wunkolo** [comment]
How's a command like option like `-c`(for `continuous`) to disable pausing?

I'd like the default behavior to be that it pauses since most end-users will be running it and would like to be able to scroll up and down the log once dumping is done rather than have it close automatically(both to verify the files dumped or for valuable diagnostic data should something go wrong).

**Comment by Measurity** [comment]
Makes sense to add an argument for it instead of silently doing something unexpectedly. I think a `-s` for `--silent` is more conventional but either way is fine.

**Comment by Wunkolo** [comment]
Added it as a `-c` flag. I also did some other small refactors such as making the injector itself open up the target path rather than the injected process so that it can be conditionally executed in the case of continuous execution. Lemme know how it goes.

**Comment by Measurity** [comment]
Thank you for the quick implementation. I just tested it and works just how I needed it 👍
