### ISSUE TITLE
Cannot dump Asphalt 9

### ISSUE THREAD

**Issue by BrandonLogandi** [Wunkolo/UWPDumper#54]
Errors out with a Remote Thread Wait Timeout error ![image](https://user-images.githubusercontent.com/59068101/126035461-da3acd94-1e5e-406f-a8c9-8e4402d7e944.png)

**Comment by umustbeloggedintododat** [comment]
Why did you close this? I'm getting this issue too, but with Assphalt 8.

**Comment by dev202112** [comment]
You can dump without problem if you use the x86 build. Asphalt9 is a 32 bit app, not 64 bit, so don't use the x64 build of UWPDumper.
