### ISSUE TITLE
Why do others use uwpdumper with ark process, but I use uwpdumper without ark process, please help me, thank you, how can I solve it?

### ISSUE THREAD

**Issue by YMY1666527646** [Wunkolo/UWPDumper#69]
Why do others use uwpdumper with ark process, but I use uwpdumper without ark process, please help me, thank you, how can I solve it?
![Uploading E66214F5-577C-4053-BC38-296CA2215248.png…]()

**Comment by YMY1666527646** [comment]
![4013EF73-A278-43C5-9308-197676412864](https://user-images.githubusercontent.com/84628110/145906540-8aca832c-2917-4296-bf76-f4a6a8a65115.png)

**Comment by Wunkolo** [comment]
I have no idea what you are talking about. I don't know what ark process" is.

**Comment by YMY1666527646** [comment]
> I have no idea what you are talking about. I don't know what ark process" is.

I mean, in the same game, I see that others can use uwpdumper, but I can't use uwpdumper

**Comment by YMY1666527646** [comment]
UWPInjector Build date (Jun  9 2021 : 06:08:11)
        └https://github.com/Wunkolo/UWPDumper
────────────────────────────────────────────────────────────────────────────────
Currently running UWP Apps:
        9052 │ StartMenuExperienceHost.exe :
                └Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy
        9004 │ RuntimeBroker.exe :
                └Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy
        9484 │ SearchUI.exe :
                └Microsoft.Windows.Cortana_cw5n1h2txyewy
        9968 │ RuntimeBroker.exe :
                └Microsoft.Windows.Cortana_cw5n1h2txyewy
       10212 │ WindowsInternal.ComposableShell.Experiences.TextInput.InputApp.exe :
                └InputApp_cw5n1h2txyewy
         784 │ WinStore.App.exe :
                └Microsoft.WindowsStore_8wekyb3d8bbwe
       12548 │ RuntimeBroker.exe :
                └Microsoft.WindowsStore_8wekyb3d8bbwe
       13188 │ SystemSettings.exe :
                └windows.immersivecontrolpanel_cw5n1h2txyewy
Enter ProcessID: 12528
Injecting into remote process: Success!
Waiting for remote thread IPC:
Remote thread wait timeout: Unable to find target thread
Press any key to continue . . .
