### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by ahmetabdi** [Wunkolo/UWPDumper#8]
Enter ProcessID: 12664
Injecting into remote process: Success!
Waiting for remote thread IPC:
Remote thread wait timeout: Unable to find target thread
Press any key to continue . . .

I've tried in calculator and multiple UWP Apps I just get a timeout, this is using a compiled version of the build x64.

OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299
System Type	x64-based PC

**Comment by idb-** [comment]
I am getting this same issue. Did you find a solution?

**Comment by ahmetabdi** [comment]
nope

**Comment by Wunkolo** [comment]
Not sure why you closed this issue immediately after opening it though. I figured it meant "nvm fixed it" or something.
I'm doing some work on #16 that might help with this.

**Comment by tunip3** [comment]
any update?

**Comment by tunip3** [comment]
> nope
try with a compiled version of #16 

[UWPDumper.zip](https://github.com/Wunkolo/UWPDumper/files/3991897/UWPDumper.zip)

**Comment by tunip3** [comment]
this issue occurs with the new game pass for pc titles

**Comment by tunip3** [comment]
> this issue occurs with the new game pass for pc titles

the issue may be a mismatched platform. Try the x86 version

**Comment by gbdrbob** [comment]
> > nope
> 
> try with a compiled version of #16
> 
> [UWPDumper.zip](https://github.com/Wunkolo/UWPDumper/files/3991897/UWPDumper.zip)

I'm experiencing the timeout issue with some UWP apps and wanted to try this but this UWPDumper is compiled against the debug version of the VC++ dlls which aren't included in the VC++ redistributable so I can't run it. Any chance of a version compiled against the public runtime library?

**Comment by gbdrbob** [comment]
> 
> 
> > this issue occurs with the new game pass for pc titles
> 
> the issue may be a mismatched platform. Try the x86 version

This worked for me on some titles! Remember, even if you're running 64 bit windows, some software binaries may be 32-bit.

**Comment by tunip3** [comment]
It may be worth closing this issue
