### ISSUE TITLE
If I use this, does this mean I can run the UWP app directly from the exe file?

### ISSUE THREAD

**Issue by TechPro424** [Wunkolo/UWPDumper#81]

**Comment by TechPro424** [comment]
If I use this utility, does it mean I can run the UWP app directly from the exe file?

**Comment by Wunkolo** [comment]
I do not believe so. As the executable is particularly written to be ran within a UWP environment and not a native windows one. It must be re-packaged into a UWP application again afaik.

**Comment by TechPro424** [comment]
How do I re-package it?

**Comment by Wunkolo** [comment]
You can search for such topics. Many people unpack and repackage UWP applications for mods.

https://www.reddit.com/r/ForzaModding/comments/8qas8i/how_to_dump_and_repackage_forza_for_modding/
https://www.reddit.com/r/halomods/comments/e5tsmu/dumping_the_ms_store_version_of_halo_mcc/

This repo is not a place for that subject matter though.
