### ISSUE TITLE
Application Crash on like 5 or 7 Files.

### ISSUE THREAD

**Issue by Dastano** [Wunkolo/UWPDumper#9]
Hey,

your UWP Dumper did always a good jop for me, sadly on Sea of Thieves, the Dumper Crash when he reach the PAK Files, I was able to extract one of them, but the big one, the game just close, not sure if there is a protection?

You may can check it out? You can try the app Free with the GamePass you get Free for 14-Days.

**Comment by Galaxxxy60** [comment]
hi!
I have the same issue with sea of thieves, I think there is a protection and it sucks...
did you find any solution?

**Comment by Wunkolo** [comment]
I haven't been able to download the game myself to test this and see what is going on with those particular but does it always crash on the particular file you are talking about? Can you post the dumper log up to the point of the crash?

**Comment by Ehnoah** [comment]
Hey.

For me It is random Sometimes already app.xml

98% IT Crash on SoT-Game.exe and 1% above Error and 1% on File 7-8 which is a PAK file.

PAK File ist also Huge a few GB. Can Post Log later.

As I wrote Game is basically free with 14 day Trial of "Game Pass" Can Post Log later.

Some people say it use TruePlay some don't. TruePlay Protect Memory which can be disabled :D

**Comment by Ehnoah** [comment]
http://prntscr.com/iwzz2a

**Comment by Ehnoah** [comment]
Tool I used was Process Hacker.

You maybe should add a Option like "-pause" so people can decide to pause process or not. Maybe pausing can cause issues on other.

**Comment by Wunkolo** [comment]
I figured that too yea. Suspending all threads when it is in the middle of other critical tasks could cause the game or software to crash in the process of dumping. Eventually I'll add a  `--pause` option so that the UWPInjector can suspend all the target process's threads except the dumper thread and I'll keep this issue open until it's done and so others can use your info for others to take as reference. 👍

**Comment by ThePotato97** [comment]
Process Hacker uses "NtSuspendProcess(processHandle);"

**Comment by Galaxxxy60** [comment]
I tried to stop the process with cheat engine with the speedhack and it didnt' work
but Process Hacker works perfectly, thank you

(by the way, the .pak files of Sea of thieves is unfortunatly encrypted, I dont think that there is a solution for that :/)

**Comment by Wunkolo** [comment]
Do you mean the the EFS encryption is preserved after the dump or do you mean the game engine itself has its own archive protection.

**Comment by ThePotato97** [comment]
Unreal engine paks use AES this is separate from the UWP protection
Read under core of this changelog
https://docs.unrealengine.com/en-us/Support/Builds/ReleaseNotes/4_16

**Comment by Ehnoah** [comment]
The Key is in a Module from WindowsStore. People reported, that the Game loads a DLL from the Windows Store, which has a Key, generated on your AccountID. Not sure how accurate is this, but people didn't found any Key in the SoT-Game.exe (there was before, but not anymore)

**Comment by Ehnoah** [comment]
Seems they added a new Protection.

Dump Path:
        DUMP
        Dumping 39 files
SeaofThieves_2.75.3442.2_x64__8wekyb3d8bbwe\AppxBlockMap.xml        20170373 bytes                    1/39
Error creating subfolder: DUMP
        operation not permitted
SeaofThieves_2.75.3442.2_x64__8wekyb3d8bbwe\AppxManifest.xml           12005 bytes                    2/39
Error creating subfolder: DUMP
        operation not permitted
.75.3442.2_x64__8wekyb3d8bbwe\AppxMetadata\CodeIntegrity.cat           13999 bytes                    3/39
Error creating subfolder: DUMP\AppxMetadata
        operation not permitted
eaofThieves_2.75.3442.2_x64__8wekyb3d8bbwe\AppxSignature.p7x           10650 bytes                    4/39
Error creating subfolder: DUMP
        operation not permitted
.3442.2_x64__8wekyb3d8bbwe\Athena\Binaries\UWP64\SoTGame.exe        92460032 bytes                    5/39
Error creating subfolder: DUMP\Athena\Binaries\UWP64
        operation not permitted
ntent\Paks\Core_6DA8E67225FDCFA78C3EA5DC3154B849-UWP64_P.pak       968306362 bytes                    6/39
Error creating subfolder: DUMP\Athena\Content\Paks
        operation not permitted
Content\Paks\Core_A693B2D79E8DCBD97A68BA3AC5BF30E4-UWP64.pak            4194 bytes                    7/39
Error creating subfolder: DUMP\Athena\Content\Paks
        operation not permitted
Content\Paks\Core_F3AF6AC8CD18A39D12936B4586D47DD2-UWP64.pak      3479744015 bytes                    8/39
Error creating subfolder: DUMP\Athena\Content\Paks
        operation not permitted
Content\Paks\Core_F5C7922DA355FD289EC1D6469E0583A7-UWP64.pak            4408 bytes                    9/39
Error creating subfolder: DUMP\Athena\Content\Paks
        operation not permitted
3442.2_x64__8wekyb3d8bbwe\Athena\Content\Paks\data-UWP64.pak       228794415 bytes                   10/39
Error creating subfolder: DUMP\Athena\Content\Paks
        operation not permitted
hieves_2.75.3442.2_x64__8wekyb3d8bbwe\cpprest140_uwp_2_9.dll         1338880 bytes                   11/39
Error creating subfolder: DUMP
        operation not permitted
ne\Binaries\ThirdParty\CoherentUIGT\UWP64\CoherentGTCore.dll        19906048 bytes                   12/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
gine\Binaries\ThirdParty\CoherentUIGT\UWP64\CoherentGTJS.dll         4150272 bytes                   13/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
ine\Binaries\ThirdParty\CoherentUIGT\UWP64\coherenticuin.dll         1859072 bytes                   14/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
ine\Binaries\ThirdParty\CoherentUIGT\UWP64\coherenticuuc.dll         1323008 bytes                   15/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
gine\Binaries\ThirdParty\CoherentUIGT\UWP64\CoherentUIGT.dll         2355200 bytes                   16/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
e\Binaries\ThirdParty\CoherentUIGT\UWP64\icudtcoherent53.dll        21529088 bytes                   17/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
ne\Binaries\ThirdParty\CoherentUIGT\UWP64\RenoirCore.UWP.dll         1575936 bytes                   18/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
d8bbwe\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64\WTF.dll          260608 bytes                   19/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\CoherentUIGT\UWP64
        operation not permitted
ThirdParty\PhysX\PhysX-3.3\UWP64\VS2015\PhysX3Common_x64.dll         1465856 bytes                   20/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\PhysX\PhysX-3.3\UWP64\VS2015
        operation not permitted
hirdParty\PhysX\PhysX-3.3\UWP64\VS2015\PhysX3Cooking_x64.dll          146944 bytes                   21/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\PhysX\PhysX-3.3\UWP64\VS2015
        operation not permitted
aries\ThirdParty\PhysX\PhysX-3.3\UWP64\VS2015\PhysX3_x64.dll         2022912 bytes                   22/39
Error creating subfolder: DUMP\Engine\Binaries\ThirdParty\PhysX\PhysX-3.3\UWP64\VS2015
        operation not permitted
2.75.3442.2_x64__8wekyb3d8bbwe\Engine\Build\build.properties              84 bytes                   23/39
Error creating subfolder: DUMP\Engine\Build
        operation not permitted
gine\Source\ThirdParty\AMD\AGS_5_2_0\lib\amd_ags_uwp_x64.dll           34304 bytes                   24/39
Error creating subfolder: DUMP\Engine\Source\ThirdParty\AMD\AGS_5_2_0\lib
        operation not permitted
t.SeaofThieves_2.75.3442.2_x64__8wekyb3d8bbwe\EraAdapter.dll          724480 bytes                   25/39
Error creating subfolder: DUMP
        operation not permitted
hieves_2.75.3442.2_x64__8wekyb3d8bbwe\Fonts\brushTipTexe.ttf          253404 bytes                   26/39
Error creating subfolder: DUMP\Fonts
        operation not permitted
_2.75.3442.2_x64__8wekyb3d8bbwe\Fonts\ManuskriptAntiquaD.ttf          464148 bytes                   27/39
Error creating subfolder: DUMP\Fonts
        operation not permitted
es_2.75.3442.2_x64__8wekyb3d8bbwe\Fonts\WindlassExtended.ttf          208764 bytes                   28/39
Error creating subfolder: DUMP\Fonts
        operation not permitted
eves_2.75.3442.2_x64__8wekyb3d8bbwe\Manifest_NonUFSFiles.txt            2015 bytes                   29/39
Error creating subfolder: DUMP
        operation not permitted
_2.75.3442.2_x64__8wekyb3d8bbwe\Microsoft.Xbox.ChatAudio.dll          792576 bytes                   30/39
Error creating subfolder: DUMP
        operation not permitted
s_2.75.3442.2_x64__8wekyb3d8bbwe\Microsoft.Xbox.GameChat.dll          816640 bytes                   31/39
Error creating subfolder: DUMP
        operation not permitted
s_2.75.3442.2_x64__8wekyb3d8bbwe\Microsoft.Xbox.Services.dll        12129792 bytes                   32/39
Error creating subfolder: DUMP
        operation not permitted
aofThieves_2.75.3442.2_x64__8wekyb3d8bbwe\Resources\Logo.png            6750 bytes                   33/39
Error creating subfolder: DUMP\Resources
        operation not permitted
ieves_2.75.3442.2_x64__8wekyb3d8bbwe\Resources\SmallLogo.png           21663 bytes                   34/39
Error creating subfolder: DUMP\Resources
        operation not permitted
es_2.75.3442.2_x64__8wekyb3d8bbwe\Resources\SplashScreen.png          115921 bytes                   35/39
Error creating subfolder: DUMP\Resources
        operation not permitted
ieves_2.75.3442.2_x64__8wekyb3d8bbwe\Resources\StoreLogo.png            2646 bytes                   36/39
Error creating subfolder: DUMP\Resources
        operation not permitted
hieves_2.75.3442.2_x64__8wekyb3d8bbwe\Resources\WideLogo.png           10831 bytes                   37/39
Error creating subfolder: DUMP\Resources
        operation not permitted
ft.SeaofThieves_2.75.3442.2_x64__8wekyb3d8bbwe\resources.pri            2960 bytes                   38/39
Error creating subfolder: DUMP
        operation not permitted
ofThieves_2.75.3442.2_x64__8wekyb3d8bbwe\xboxservices.config              98 bytes                   39/39
Error creating subfolder: DUMP
        operation not permitted
Dump complete!
        Path:
        DUMP
